-- ============================================================
-- SCV-01 seed — Albert Street Time-Travel Art Nouveau Hunt
-- Source-backed Riga hunt with a time_travel_photo prompt.
-- Run after base SCV migrations. This seed also defensively adds
-- artifact/source and prompt_metadata columns used by newer SCV prompts.
-- ============================================================

ALTER TABLE public.hunts
  ADD COLUMN IF NOT EXISTS artifact_kind TEXT NOT NULL DEFAULT 'scavenger_hunt',
  ADD COLUMN IF NOT EXISTS artifact_version INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS created_via TEXT NOT NULL DEFAULT 'human'
    CHECK (created_via IN ('human', 'ai_assisted', 'ai_generated')),
  ADD COLUMN IF NOT EXISTS source_links JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS ai_prompt TEXT,
  ADD COLUMN IF NOT EXISTS generation_notes TEXT;

ALTER TABLE public.hunt_stops
  ADD COLUMN IF NOT EXISTS parent_hint TEXT,
  ADD COLUMN IF NOT EXISTS prompt_metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT conname INTO constraint_name
  FROM pg_constraint
  WHERE conrelid = 'public.hunt_stops'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%prompt_kind%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.hunt_stops DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

ALTER TABLE public.hunt_stops
  ADD CONSTRAINT hunt_stops_prompt_kind_check
  CHECK (prompt_kind IN (
    'text',
    'multiple_choice',
    'photo',
    'observation',
    'audio',
    'drawing',
    'time_travel_photo'
  ));

DO $$
DECLARE
  v_hunt_id UUID;
  v_wiki TEXT := 'https://en.wikipedia.org/wiki/Albert_Street,_Riga';
  v_latvians TEXT := 'https://www.latvians.com/index.php?en%2FTrips%2FFeatures-AlbertaIela%2FNo-00-Alberta%2Findex.ssi=';
  v_old_image TEXT := 'https://latvians.com/en/Trips/Features-AlbertaIela/No-00-Alberta/figures/24-Albert-strasse-grayscale.jpg';
  v_osm TEXT := 'https://www.openstreetmap.org/search?query=Alberta%20iela%2C%20Riga';
BEGIN
  SELECT id INTO v_hunt_id
  FROM public.hunts
  WHERE slug = 'riga-albert-street-time-travel';

  IF v_hunt_id IS NULL THEN
    INSERT INTO public.hunts (
      slug, title, blurb, cover_emoji, host_name, city, country_code,
      primary_theme, age_min, age_max, duration_minutes, difficulty,
      est_cost_cents, distance_meters, credits, status, published_at,
      artifact_kind, artifact_version, created_via, source_links, generation_notes
    ) VALUES (
      'riga-albert-street-time-travel',
      'Albert Street Time-Travel Art Nouveau Hunt',
      'A short Riga Art Nouveau walk where kids line up an old Albertstraße photo with today’s Alberta iela and hunt for architects, faces, towers, and museum clues.',
      '🕰️',
      'FamActify Original',
      'Rīga',
      'LV',
      'art',
      7,
      14,
      45,
      'easy',
      0,
      255,
      'Source facts: Wikipedia page “Albert Street, Riga”; Latvians.com “Alberta iela, Albert Street” feature and historical Albertstraße image; coordinates checked with OpenStreetMap/Nominatim for Alberta iela addresses.',
      'published',
      '2026-05-03T00:00:00Z',
      'scavenger_hunt',
      1,
      'human',
      jsonb_build_array(v_wiki, v_latvians, v_old_image, v_osm),
      'Generated by Codex from user-provided Wikipedia page and historical image URL. Facts are paraphrased and source-backed; no invented historical image.'
    )
    RETURNING id INTO v_hunt_id;
  ELSE
    UPDATE public.hunts
    SET
      title = 'Albert Street Time-Travel Art Nouveau Hunt',
      blurb = 'A short Riga Art Nouveau walk where kids line up an old Albertstraße photo with today’s Alberta iela and hunt for architects, faces, towers, and museum clues.',
      cover_emoji = '🕰️',
      host_name = 'FamActify Original',
      city = 'Rīga',
      country_code = 'LV',
      primary_theme = 'art',
      age_min = 7,
      age_max = 14,
      duration_minutes = 45,
      difficulty = 'easy',
      est_cost_cents = 0,
      distance_meters = 255,
      credits = 'Source facts: Wikipedia page “Albert Street, Riga”; Latvians.com “Alberta iela, Albert Street” feature and historical Albertstraße image; coordinates checked with OpenStreetMap/Nominatim for Alberta iela addresses.',
      status = 'published',
      published_at = COALESCE(published_at, '2026-05-03T00:00:00Z'),
      artifact_kind = 'scavenger_hunt',
      artifact_version = 1,
      created_via = 'human',
      source_links = jsonb_build_array(v_wiki, v_latvians, v_old_image, v_osm),
      generation_notes = 'Generated by Codex from user-provided Wikipedia page and historical image URL. Facts are paraphrased and source-backed; no invented historical image.'
    WHERE id = v_hunt_id;
  END IF;

  DELETE FROM public.hunt_stops WHERE hunt_id = v_hunt_id;
  DELETE FROM public.hunt_sponsors WHERE hunt_id = v_hunt_id;

  INSERT INTO public.hunt_sponsors (hunt_id, name, url, sort_order)
  VALUES (v_hunt_id, 'FamActify', 'https://famactify.com', 0);

  INSERT INTO public.hunt_stops (
    hunt_id, stop_order, title, lat, lon, address, clue_text, parent_hint,
    prompt_kind, prompt_question, prompt_options, prompt_correct, prompt_photo_subject,
    prompt_metadata, reveal_fun_fact
  ) VALUES
  (
    v_hunt_id, 0, 'Time-Travel View: Albertstraße → Alberta iela', 56.95904, 24.109712, 'Alberta iela, Centrs, Rīga',
    'Start on Alberta iela where you can safely see the street façades in a row. Hold the phone up and try to line the old Albertstraße image with today’s buildings.',
    'Use building edges, balconies, roofline shapes, and the curve of the street to help line up the historical image. Stay on the sidewalk.',
    'time_travel_photo',
    'Line up the historical Albertstraße view with today’s Alberta iela and capture your best match.',
    NULL,
    NULL,
    NULL,
    jsonb_build_object(
      'timeTravelImageUrl', v_old_image,
      'timeTravelCaption', 'Historical grayscale Albertstraße view from Latvians.com “Alberta iela, Albert Street” feature. Use only as a visual alignment overlay; stay safely on the sidewalk.',
      'timeTravelOpacity', 0.5
    ),
    'Wikipedia says Albert Street was built in 1901 and named after Bishop Albert, the founder of Riga in 1201. Latvians.com presents the street as one of Riga’s great Jugendstil / Art Nouveau treasures.'
  ),
  (
    v_hunt_id, 1, 'Name Detective: Who Was Albert?', 56.9589533, 24.1110224, 'Alberta iela 2A, Rīga, LV-1010',
    'Look for the street name “Alberta iela.” The street name itself is your clue: who is Albert?',
    'The source-backed answer is Bishop Albert. Wikipedia says he founded Riga in 1201.',
    'multiple_choice',
    'Albert Street is named after which historical figure?',
    '["Bishop Albert","Albert Einstein","Queen Alberta","A ship called Albert"]'::jsonb,
    '["Bishop Albert"]'::jsonb,
    NULL,
    '{}'::jsonb,
    'Wikipedia identifies the street’s namesake as Bishop Albert, connected with Riga’s founding in 1201.'
  ),
  (
    v_hunt_id, 2, 'Eisenstein Façade Hunt', 56.9593002, 24.109658, 'Alberta iela 8, Rīga, LV-1010',
    'Find one of the most dramatic façades on the street. Look up for faces, masks, balconies, curves, and sculptural details.',
    'Wikipedia lists several Alberta iela buildings by Mikhail Eisenstein, including numbers 2a, 4, 6, 8, and 13.',
    'multiple_choice',
    'Which architect designed many of the apartment buildings on Alberta iela?',
    '["Mikhail Eisenstein","Eižens Laube only","Antoni Gaudí","Frank Lloyd Wright"]'::jsonb,
    '["Mikhail Eisenstein"]'::jsonb,
    NULL,
    '{}'::jsonb,
    'Wikipedia says many apartment buildings along Albert Street were designed by Mikhail Eisenstein, whose decorative creativity is reflected in the street’s Art Nouveau façades.'
  ),
  (
    v_hunt_id, 3, 'No. 9: Pēkšēns Pattern Spotter', 56.9590141, 24.109163, 'Alberta iela 9, Rīga, LV-1010',
    'Stand safely near No. 9 and choose one decorative detail: a line, curve, plant shape, face, window, or balcony edge.',
    'Wikipedia lists Alberta iela 9 as a residential building by Konstantīns Pēkšēns, built in 1901.',
    'drawing',
    'Draw one small pattern or shape you notice on the façade.',
    NULL,
    NULL,
    NULL,
    '{"drawingSubject":"One façade detail from Alberta iela 9: curve, window, plant shape, face, or balcony edge"}'::jsonb,
    'Wikipedia lists Alberta iela 9 as a residential building by Konstantīns Pēkšēns, built in 1901 — the same year Wikipedia gives for the street’s construction start.'
  ),
  (
    v_hunt_id, 4, 'No. 12: Museum House', 56.9596096, 24.1085166, 'Alberta iela 12, Rīga, LV-1010',
    'Walk to No. 12. Find the museum connection and notice how the entrance, tower, or windows feel different from a plain apartment block.',
    'Wikipedia says Pēkšēns’ former residence at No. 12 has housed the Riga Art Nouveau Museum since April 2009.',
    'multiple_choice',
    'What museum is located at Alberta iela 12?',
    '["Riga Art Nouveau Museum","Riga Zoo","Latvian War Museum","House of the Blackheads Museum"]'::jsonb,
    '["Riga Art Nouveau Museum"]'::jsonb,
    NULL,
    '{}'::jsonb,
    'Wikipedia says No. 12 was designed by Konstantīns Pēkšēns and Eižens Laube, and that Pēkšēns’ former residence there has housed the Riga Art Nouveau Museum since April 2009.'
  ),
  (
    v_hunt_id, 5, 'No. 13: Final Detail Memory', 56.9592118, 24.1078606, 'Alberta iela 13, Rīga, LV-1010',
    'Finish near No. 13. Look up one last time and take a privacy-safe close-up of a public building detail — no faces, no private windows.',
    'Wikipedia lists Alberta iela 13 as a residential building by Mikhail Eisenstein, built in 1904, and says it is now owned by Riga Graduate School of Law.',
    'photo',
    'Take one privacy-safe photo of an Art Nouveau detail you want to remember.',
    NULL,
    NULL,
    'Alberta iela public façade detail without people’s faces',
    '{}'::jsonb,
    'Wikipedia lists Alberta iela 13 as another Mikhail Eisenstein building from 1904, and notes that it is now owned by Riga Graduate School of Law.'
  );
END $$;
